---
- name: Installation des packages monit.
  ansible.builtin.apt:
    name: "{{ liste_packages }}"
    state: latest
    update_cache: true
  tags:
    - packages

- name: Arrêt du service monit.
  ansible.builtin.service:
    name: monit
    state: stopped
    enabled: false
  tags:
    - config

- name: Création du répertoire de surcharge pour monit.
  ansible.builtin.file:
    path: /usr/lib/systemd/system/monit.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - config

- name: Durcissement de monit.
  ansible.builtin.template:
    src: durcissemnt.j2
    dest: /usr/lib/systemd/system/monit.service.d/durcissemnt.conf
    backup: false
    owner: root
    group: root
    mode: '0644'
  tags:
    - config

- name: Copie du fichier de règle du pare-feu.
  ansible.builtin.template:
    src: monit_firewall.j2
    dest: /etc/firewalld/services/monit.xml
    owner: root
    group: root
    mode: '0640'
    backup: false
  tags:
    - firewalld

- name: Ouverture du pare-feu pour monit.
  ansible.posix.firewalld:
    service: monit
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewalld


- name: Calcule des hash des fichiers de config.
  import_tasks: hash.yml

- name: Installation des profiles.
  import_tasks: profiles.yml